In [1]:
import pandas as pd
import numpy as np

In [3]:
url = "https://raw.githubusercontent.com/github/innovationgraph/refs/heads/main/data/languages.csv"
lang_data = pd.read_csv(url)

In [4]:
lang_data

        num_pushers          language language_type iso2_code  year  quarter
0              2066              HTML        markup        AE  2020        1
1              1627               CSS        markup        AE  2020        1
2               288  Jupyter Notebook        markup        AE  2020        1
3               108               Vue        markup        AE  2020        1
4              1734        JavaScript   programming        AE  2020        1
...             ...               ...           ...       ...   ...      ...
144624          131          Procfile   programming        ZW  2025        1
144625          128             Swift   programming        ZW  2025        1
144626          111       Objective-C   programming        ZW  2025        1
144627          105              Dart   programming        ZW  2025        1
144628          103             CMake   programming        ZW  2025        1

[144629 rows x 6 columns]

In [8]:
import pandas as pd

class LanguageData:
    def __init__(self, data_source):
        if isinstance(data_source, str):
            self.data = pd.read_csv(data_source)
        else:
            self.data = data_source
        
        # Attributes
        self.number_of_years = self.data['year'].nunique()
        self.number_of_countries = self.data['iso2_code'].nunique()
        self.number_of_unique_quarters = self.data['quarter'].nunique()
    
    def get_programmers(self, country_code, language, year, quarter):
        """Get number of programmers for specific country, language, year, quarter"""
        result = self.data[
            (self.data['iso2_code'] == country_code) &
            (self.data['language'] == language) &
            (self.data['year'] == year) &
            (self.data['quarter'] == quarter)
        ]
        return result['num_pushers'].iloc[0] if not result.empty else None

In [10]:

# Usage example:
url = "https://raw.githubusercontent.com/github/innovationgraph/refs/heads/main/data/languages.csv"
analyzer = LanguageData(url)

In [15]:
analyzer.data

        num_pushers          language language_type iso2_code  year  quarter
0              2066              HTML        markup        AE  2020        1
1              1627               CSS        markup        AE  2020        1
2               288  Jupyter Notebook        markup        AE  2020        1
3               108               Vue        markup        AE  2020        1
4              1734        JavaScript   programming        AE  2020        1
...             ...               ...           ...       ...   ...      ...
144624          131          Procfile   programming        ZW  2025        1
144625          128             Swift   programming        ZW  2025        1
144626          111       Objective-C   programming        ZW  2025        1
144627          105              Dart   programming        ZW  2025        1
144628          103             CMake   programming        ZW  2025        1

[144629 rows x 6 columns]

In [12]:
analyzer.number_of_years

6

In [13]:
analyzer.number_of_countries

171

In [14]:
analyzer.number_of_unique_quarters

4

In [19]:
analyzer.get_programmers("PE", "HTML", 2020, 3)

8854

In [ ]:
analyzer.get_programmers("PE", "HTML", 2020, 3)

In [ ]:


print(f"Years: {analyzer.number_of_years}")
print(f"Countries: {analyzer.number_of_countries}")
print(f"Quarters: {analyzer.number_of_unique_quarters}")

# Get HTML programmers in Peru for 2022 Q2
result = analyzer.get_programmers('PE', 'HTML', 2022, 2)
print(f"Peru HTML 2022 Q2: {result}")